### ISSUE TITLE
Can't find payment by psp reference for AUTHORISATION event

### ISSUE THREAD

**Issue by Krysik** [Adyen/adyen-commercetools#1191] opened 2024-07-30 12:16 UTC
**Describe the bug**

On the production environment, I noticed an error in the notification app that says `Cannot read properties of undefined (reading 'version')` it seems like it cannot find a payment when `AUTHORIZATION` event has been triggered.

I'm using notification in version `11.5.3`

**To Reproduce**
1. Trigger the `AUTHORIZATION` event

**Expected behavior**
Payment should be received or log should not show in case of `AUTHORIZATION` event.

**Screenshots**

```
{
  "name": "ctp-adyen-integration-notifications",
  "pid": 1,
  "level": 50,
  "notification": [
    {
      "eventCode": "AUTHORISATION",
      "eventDate": "2024-07-04T23:49:36+02:00",
      "pspReference": "<PSP_REFERENCE>",
      "success": "true"
    }
  ],
  "cause": {
    "message": "Cannot read properties of undefined (reading 'version')",
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of undefined (reading 'version')\n    at updatePaymentWithRepeater (file:///app/src/handler/notification/notification.handler.js:73:32)\n    at Object.processNotification (file:///app/src/handler/notification/notification.handler.js:58:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async handleNotification (file:///app/src/api/notification/notification.controller.js:27:7)\n    at async Server.<anonymous> (file:///app/src/server.js:20:9)"
  },
  "msg": "Unexpected exception occurred.",
  "time": "2024-07-04T21:49:36.725Z",
  "v": 0
}
```

**Comment by logeecom** [comment] 2024-08-08 13:34
Hey @Krysik 

Thank you for reaching out!

Our team will check the issue you reported and we will get back to you with more information.

Best regards

Logeecom team.

**Comment by logeecom** [comment] 2024-08-16 15:31
Hey @Krysik 

We were not able to reproduce this issue locally, but we have updated the notification integration where we believe the problem originated.
These changes will be included in the next release, which is expected next week.

Best regards.

**Comment by logeecom** [comment] 2024-08-22 08:47
Hey,

The new version [(v11.5.6) has been released](https://github.com/Adyen/adyen-commercetools/releases/tag/v11.5.6).

Best regards.

**Closed** 2024-08-22 08:47 UTC
