### ISSUE TITLE
Parsing error in extension module

### ISSUE THREAD

**Issue by andihalberkamp** [Adyen/adyen-commercetools#1219] opened 2024-11-04 08:02 UTC
hi,

I am encountering a persistent issue in our Adyen extension  to JSON parsing. The error details are as follows:

Error Message:

```
javascript
Code kopieren
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at _getPaymentObject (file:///app/src/api/payment/payment.controller.js:73:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processRequest (file:///app/src/api/payment/payment.controller.js:30:21)
    at async Server.<anonymous> (file:///app/src/server.js:26:9)
Context:

Function: _getPaymentObject in payment.controller.js at line 73
Invocation: processRequest in payment.controller.js at line 30
Server Entry Point: server.js at line 26
```
We tried to debug that error, but we didn`t find any hint of why the parsing error occures.
Maybe you can help up to fix this issue?

Best regards,

Andi

**Comment by adyen-integrations-support** [comment] 2024-11-07 10:08
Hello,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

We will take this issue into consideration as soon as possible.

Best regards

**Comment by andihalberkamp** [comment] 2024-11-21 16:59
Hi,
Were you able to take a look at this issue? or can you add a debug log to the code, so that I can inspect that issue?
Best Andi

**Comment by adyen-integrations-support** [comment] 2024-11-29 14:11
Hi @andihalberkamp ,

The request body that the extension attempts to parse as JSON is received from the Commercetools API. The extension catches this type of error and logs it (referenced in payment.controller.js at line 76).

Could you please provide us with this specific log entry? Having access to the log details will help us better understand the root cause of this issue and assist you in resolving it effectively.

Best regards

**Closed** 2024-12-14 16:48 UTC
